language: node_js
node_js:
- '8.10.0'
- '10'
- '12'
before_install:
  - yarn global add greenkeeper-lockfile@1
  - sudo apt-get update -y
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker info
before_script: greenkeeper-lockfile-update
script: yarn test
after_script: greenkeeper-lockfile-upload
after_success: yarn coverage
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    tags: true
    repo: lifeomic/lambda-tools
    node: '8.10.0'

sudo: required
services:
  - docker
